/**
 * Generated TypeScript types from OpenAPI specification
 * DO NOT EDIT MANUALLY - Generated by openapi-typescript
 */

export type PackStatus = 'draft' | 'approved' | 'retired';
export type PackSource = 'manual' | 'ai' | 'hybrid';
export type QuestionType = 'single' | 'multi' | 'scale' | 'text' | 'number' | 'yesno';

export interface QuestionOption {
  i18nKey: string;
  value: string;
  order: number;
}

export interface VisibilityCondition {
  questionKey: string;
  equals: string | number | boolean;
}

export interface VisibilityRule {
  anyOf?: VisibilityCondition[];
  allOf?: VisibilityCondition[];
  not?: VisibilityRule;
}

export interface QuestionDef {
  key: string;
  type: QuestionType;
  i18nKey: string;
  required?: boolean;
  options?: QuestionOption[];
  visibility?: VisibilityRule;
  aiHint?: string;
}

export interface MicroserviceDef {
  id: string;
  category: string;
  name: string;
  slug: string;
  i18nPrefix: string;
  questions: QuestionDef[];
}

export interface Pack {
  pack_id: string;
  micro_slug: string;
  version: number;
  status: PackStatus;
  source: PackSource;
  prompt_hash?: string | null;
  content: MicroserviceDef;
  created_by?: string | null;
  created_at: string;
  approved_at?: string | null;
  approved_by?: string | null;
  is_active: boolean;
  ab_test_id?: string | null;
}

export interface ImportPackPayload {
  slug: string;
  content: MicroserviceDef;
  source: PackSource;
  status?: 'draft' | 'approved';
}

export interface PackComparison {
  active: Pack | null;
  draft: Pack | null;
  versionHistory: Pack[];
  metrics: any | null;
}

export interface QuestionMetrics {
  slug: string;
  pack_id: string;
  question_key: string;
  views: number;
  answers: number;
  dropoffs: number;
  avg_time_ms: number;
  updated_at: string;
}

export interface PackFilters {
  status?: PackStatus;
  source?: PackSource;
  slug?: string;
  ibizaSpecific?: boolean;
}
