import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Brain, Target, Zap, AlertCircle, TrendingUp, MapPin, Clock, Star } from 'lucide-react';
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ScatterChart, Scatter } from 'recharts';
import { supabase } from '@/integrations/supabase/client';

interface PredictiveInsight {
  title: string;
  prediction: string;
  confidence: number;
  impact: 'high' | 'medium' | 'low';
  category: string;
  description: string;
}

interface GeographicData {
  region: string;
  revenue: number;
  jobs: number;
  professionals: number;
  demand_score: number;
}

interface ServicePerformance {
  service: string;
  revenue: number;
  job_count: number;
  avg_rating: number;
  completion_rate: number;
  trend: 'up' | 'down' | 'stable';
}

const COLORS = ['hsl(var(--primary))', 'hsl(var(--secondary))', '#0088FE', '#00C49F', '#FFBB28', '#FF8042'];

export const BusinessIntelligencePanel = () => {
  const [loading, setLoading] = useState(true);
  const [insights, setInsights] = useState<PredictiveInsight[]>([]);
  const [geoData, setGeoData] = useState<GeographicData[]>([]);
  const [servicePerf, setServicePerf] = useState<ServicePerformance[]>([]);
  const [seasonalData, setSeasonalData] = useState<any[]>([]);

  useEffect(() => {
    loadBusinessIntelligence();
  }, []);

  const loadBusinessIntelligence = async () => {
    try {
      setLoading(true);

      // Mock predictive insights - would be generated by AI analysis
      const mockInsights: PredictiveInsight[] = [
        {
          title: 'Peak Demand Forecast',
          prediction: '35% increase in home maintenance requests expected next week',
          confidence: 87,
          impact: 'high',
          category: 'Demand',
          description: 'Weather patterns and seasonal trends indicate surge in outdoor work requests'
        },
        {
          title: 'Professional Shortage Alert',
          prediction: 'Plumbing services may experience 15% shortage in availability',
          confidence: 72,
          impact: 'medium',
          category: 'Supply',
          description: 'Current booking vs professional availability analysis'
        },
        {
          title: 'Revenue Opportunity',
          prediction: 'Premium services could increase revenue by $45K monthly',
          confidence: 91,
          impact: 'high',
          category: 'Revenue',
          description: 'Client spending pattern analysis reveals untapped premium market'
        },
        {
          title: 'Retention Risk',
          prediction: '12% of professionals show early churn indicators',
          confidence: 68,
          impact: 'medium',
          category: 'Retention',
          description: 'Engagement metrics and earning patterns suggest risk factors'
        }
      ];

      // Mock geographic performance data
      const mockGeoData: GeographicData[] = [
        { region: 'Downtown', revenue: 125000, jobs: 450, professionals: 89, demand_score: 9.2 },
        { region: 'Suburbs North', revenue: 98000, jobs: 320, professionals: 67, demand_score: 7.8 },
        { region: 'Suburbs South', revenue: 110000, jobs: 380, professionals: 73, demand_score: 8.4 },
        { region: 'East District', revenue: 87000, jobs: 290, professionals: 54, demand_score: 6.9 },
        { region: 'West District', revenue: 92000, jobs: 315, professionals: 61, demand_score: 7.3 }
      ];

      // Mock service performance data
      const mockServicePerf: ServicePerformance[] = [
        { service: 'Home Cleaning', revenue: 45000, job_count: 234, avg_rating: 4.7, completion_rate: 97, trend: 'up' },
        { service: 'Plumbing', revenue: 38000, job_count: 89, avg_rating: 4.5, completion_rate: 94, trend: 'stable' },
        { service: 'Electrical', revenue: 42000, job_count: 76, avg_rating: 4.8, completion_rate: 96, trend: 'up' },
        { service: 'Handyman', revenue: 52000, job_count: 187, avg_rating: 4.4, completion_rate: 92, trend: 'down' },
        { service: 'Landscaping', revenue: 36000, job_count: 143, avg_rating: 4.6, completion_rate: 89, trend: 'up' }
      ];

      // Mock seasonal trends
      const mockSeasonalData = [
        { month: 'Jan', cleaning: 340, plumbing: 120, electrical: 80, landscaping: 45 },
        { month: 'Feb', cleaning: 385, plumbing: 135, electrical: 92, landscaping: 52 },
        { month: 'Mar', cleaning: 420, plumbing: 180, electrical: 110, landscaping: 180 },
        { month: 'Apr', cleaning: 450, plumbing: 160, electrical: 125, landscaping: 340 },
        { month: 'May', cleaning: 480, plumbing: 145, electrical: 140, landscaping: 420 },
        { month: 'Jun', cleaning: 520, plumbing: 130, electrical: 160, landscaping: 480 }
      ];

      setInsights(mockInsights);
      setGeoData(mockGeoData);
      setServicePerf(mockServicePerf);
      setSeasonalData(mockSeasonalData);

    } catch (error) {
      console.error('Error loading business intelligence:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <Brain className="w-8 h-8 text-primary" />
        <div>
          <h2 className="text-2xl font-bold">Business Intelligence</h2>
          <p className="text-muted-foreground">AI-powered insights and predictions</p>
        </div>
      </div>

      <Tabs defaultValue="insights" className="space-y-6">
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="insights">AI Insights</TabsTrigger>
          <TabsTrigger value="geographic">Geographic</TabsTrigger>
          <TabsTrigger value="services">Services</TabsTrigger>
          <TabsTrigger value="seasonal">Seasonal</TabsTrigger>
        </TabsList>

        <TabsContent value="insights">
          <div className="grid gap-4">
            {insights.map((insight, index) => (
              <Card key={index} className="hover-scale">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {insight.category === 'Demand' && <Target className="w-5 h-5 text-blue-500" />}
                      {insight.category === 'Supply' && <AlertCircle className="w-5 h-5 text-orange-500" />}
                      {insight.category === 'Revenue' && <TrendingUp className="w-5 h-5 text-green-500" />}
                      {insight.category === 'Retention' && <Zap className="w-5 h-5 text-red-500" />}
                      <div>
                        <CardTitle className="text-lg">{insight.title}</CardTitle>
                        <Badge variant={
                          insight.impact === 'high' ? 'destructive' : 
                          insight.impact === 'medium' ? 'default' : 'secondary'
                        }>
                          {insight.impact} impact
                        </Badge>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm text-muted-foreground">Confidence</div>
                      <div className="text-2xl font-bold">{insight.confidence}%</div>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-lg font-medium mb-2">{insight.prediction}</p>
                  <p className="text-sm text-muted-foreground">{insight.description}</p>
                  <Progress value={insight.confidence} className="mt-3" />
                </CardContent>
              </Card>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="geographic">
          <div className="grid lg:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MapPin className="w-5 h-5" />
                  Regional Performance
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={geoData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="region" />
                    <YAxis />
                    <Tooltip />
                    <Bar dataKey="revenue" fill="hsl(var(--primary))" />
                  </BarChart>
                </ResponsiveContainer>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Regional Metrics</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {geoData.map((region, index) => (
                    <div key={index} className="flex items-center justify-between p-3 border rounded-lg">
                      <div>
                        <h4 className="font-medium">{region.region}</h4>
                        <p className="text-sm text-muted-foreground">
                          {region.jobs} jobs • {region.professionals} professionals
                        </p>
                      </div>
                      <div className="text-right">
                        <div className="font-bold">${region.revenue.toLocaleString()}</div>
                        <div className="text-sm">
                          Demand: <span className="font-medium">{region.demand_score}/10</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="services">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>Service Performance Overview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  {servicePerf.map((service, index) => (
                    <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                      <div className="flex items-center gap-4">
                        <div>
                          <h4 className="font-medium">{service.service}</h4>
                          <div className="flex items-center gap-4 text-sm text-muted-foreground">
                            <span>{service.job_count} jobs</span>
                            <div className="flex items-center gap-1">
                              <Star className="w-3 h-3 fill-yellow-400 text-yellow-400" />
                              {service.avg_rating}
                            </div>
                            <span>{service.completion_rate}% completion</span>
                          </div>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="font-bold">${service.revenue.toLocaleString()}</div>
                        <Badge variant={
                          service.trend === 'up' ? 'default' :
                          service.trend === 'down' ? 'destructive' : 'secondary'
                        }>
                          {service.trend === 'up' && <TrendingUp className="w-3 h-3 mr-1" />}
                          {service.trend === 'down' && <TrendingUp className="w-3 h-3 mr-1 rotate-180" />}
                          {service.trend}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="seasonal">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Clock className="w-5 h-5" />
                Seasonal Trends Analysis
              </CardTitle>
              <CardDescription>Service demand patterns throughout the year</CardDescription>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={400}>
                <BarChart data={seasonalData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="cleaning" stackId="a" fill={COLORS[0]} />
                  <Bar dataKey="plumbing" stackId="a" fill={COLORS[1]} />
                  <Bar dataKey="electrical" stackId="a" fill={COLORS[2]} />
                  <Bar dataKey="landscaping" stackId="a" fill={COLORS[3]} />
                </BarChart>
              </ResponsiveContainer>
              <div className="flex flex-wrap gap-4 mt-4 justify-center">
                {['cleaning', 'plumbing', 'electrical', 'landscaping'].map((service, index) => (
                  <div key={service} className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full" style={{ backgroundColor: COLORS[index] }}></div>
                    <span className="text-sm capitalize">{service}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
};