/**
 * Generated React Query hooks from OpenAPI specification
 * DO NOT EDIT MANUALLY - Generated by orval
 * 
 * These are drop-in replacements for manual useQuery/useMutation calls
 */

import { useQuery, useMutation, useQueryClient, UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { customInstance } from '@/lib/api';
import type { Pack, PackFilters, ImportPackPayload, PackComparison } from '../../types';

// Query keys factory
export const packsKeys = {
  all: ['packs'] as const,
  lists: () => [...packsKeys.all, 'list'] as const,
  list: (filters?: PackFilters) => [...packsKeys.lists(), filters] as const,
  details: () => [...packsKeys.all, 'detail'] as const,
  detail: (id: string) => [...packsKeys.details(), id] as const,
  comparison: (slug: string) => [...packsKeys.all, 'comparison', slug] as const,
  metrics: (packId: string) => [...packsKeys.all, 'metrics', packId] as const,
};

// List packs
export const useGetAdminPacks = (
  filters?: PackFilters,
  options?: Omit<UseQueryOptions<Pack[], Error>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<Pack[], Error>({
    queryKey: packsKeys.list(filters),
    queryFn: async ({ signal }) => {
      return customInstance<Pack[]>({
        url: '/api/v1/admin/packs',
        method: 'GET',
        params: filters,
        signal,
      });
    },
    ...options,
  });
};

// Import pack
export const usePostAdminPacksImport = (
  options?: UseMutationOptions<Pack, Error, ImportPackPayload>
) => {
  const queryClient = useQueryClient();

  return useMutation<Pack, Error, ImportPackPayload>({
    mutationFn: async (data) => {
      return customInstance<Pack>({
        url: '/api/v1/admin/packs/import',
        method: 'POST',
        data,
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: packsKeys.lists() });
    },
    ...options,
  });
};

// Approve pack
export const usePostAdminPacksApprove = (
  options?: UseMutationOptions<Pack, Error, { packId: string }>
) => {
  const queryClient = useQueryClient();

  return useMutation<Pack, Error, { packId: string }>({
    mutationFn: async ({ packId }) => {
      return customInstance<Pack>({
        url: `/api/v1/admin/packs/${packId}/approve`,
        method: 'POST',
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: packsKeys.lists() });
    },
    ...options,
  });
};

// Activate pack
export const usePostAdminPacksActivate = (
  options?: UseMutationOptions<Pack, Error, { packId: string }>
) => {
  const queryClient = useQueryClient();

  return useMutation<Pack, Error, { packId: string }>({
    mutationFn: async ({ packId }) => {
      return customInstance<Pack>({
        url: `/api/v1/admin/packs/${packId}/activate`,
        method: 'POST',
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: packsKeys.lists() });
    },
    ...options,
  });
};

// Retire pack
export const usePostAdminPacksRetire = (
  options?: UseMutationOptions<Pack, Error, { packId: string }>
) => {
  const queryClient = useQueryClient();

  return useMutation<Pack, Error, { packId: string }>({
    mutationFn: async ({ packId }) => {
      return customInstance<Pack>({
        url: `/api/v1/admin/packs/${packId}/retire`,
        method: 'POST',
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: packsKeys.lists() });
    },
    ...options,
  });
};

// Get pack comparison
export const useGetAdminPacksComparison = (
  slug: string,
  options?: Omit<UseQueryOptions<PackComparison, Error>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<PackComparison, Error>({
    queryKey: packsKeys.comparison(slug),
    queryFn: async ({ signal }) => {
      return customInstance<PackComparison>({
        url: `/api/v1/admin/packs/comparison/${slug}`,
        method: 'GET',
        signal,
      });
    },
    enabled: !!slug,
    ...options,
  });
};

// Get pack metrics
export const useGetAdminPacksMetrics = (
  packId: string,
  options?: Omit<UseQueryOptions<any, Error>, 'queryKey' | 'queryFn'>
) => {
  return useQuery<any, Error>({
    queryKey: packsKeys.metrics(packId),
    queryFn: async ({ signal }) => {
      return customInstance<any>({
        url: `/api/v1/admin/packs/${packId}/metrics`,
        method: 'GET',
        signal,
      });
    },
    enabled: !!packId,
    ...options,
  });
};
