-- Proveedores Demo Profiles - Correct Values
DO $$
DECLARE v_m uuid; v_b uuid; v_s1 uuid; v_s2 uuid; v_s3 uuid; v_s4 uuid; v_s5 uuid;
BEGIN
  INSERT INTO services (category,subcategory,micro) VALUES ('proveedores','materiales','cementos') RETURNING id INTO v_s1;
  INSERT INTO services (category,subcategory,micro) VALUES ('proveedores','materiales','aislantes') RETURNING id INTO v_s2;
  INSERT INTO services (category,subcategory,micro) VALUES ('proveedores','materiales','impermeabilizacion') RETURNING id INTO v_s3;
  INSERT INTO services (category,subcategory,micro) VALUES ('proveedores','equipos','maquinaria') RETURNING id INTO v_s4;
  INSERT INTO services (category,subcategory,micro) VALUES ('proveedores','equipos','epis') RETURNING id INTO v_s5;
  SELECT id INTO v_m FROM auth.users WHERE email = 'demo+materiales@ibizafair.com';
  IF v_m IS NULL THEN INSERT INTO auth.users (id,instance_id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change) VALUES (gen_random_uuid(),'00000000-0000-0000-0000-000000000000','demo+materiales@ibizafair.com',crypt('Demo123!',gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now(),'','','','') RETURNING id INTO v_m; END IF;
  INSERT INTO profiles (id,full_name,phone) VALUES (v_m,'Ibiza Materiales','+34 600 345 112') ON CONFLICT (id) DO NOTHING;
  INSERT INTO user_roles (user_id,role) VALUES (v_m,'professional') ON CONFLICT DO NOTHING;
  INSERT INTO professional_profiles (user_id,business_name,primary_trade,bio,contact_phone,whatsapp,contact_email,social_links,experience_years,team_size,languages,emergency_service,max_projects_in_parallel,min_project_value,max_project_value,subsector_tags,unique_selling_points,ideal_clients,is_demo_profile,featured_at_events) VALUES (v_m,'Ibiza Materiales & Suministros','proveedores','Proveedor integral de materiales.','+34 600 345 112','+34 600 345 112','demo+materiales@ibizafair.com','{"instagram":"https://instagram.com/ibizamateriales"}'::jsonb,'18',12,'["ES","EN"]'::jsonb,true,15,100,30000,'["Materiales","Aislantes"]'::jsonb,'["Entrega 24h","Stock"]'::jsonb,'Constructoras',true,'["ibiza-fair-2025"]'::jsonb) ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO professional_service_items (professional_id,service_id,name,description,category,pricing_type,display_order) VALUES (v_m,v_s1,'Cementos y morteros','Primeras marcas','proveedores','quote',1),(v_m,v_s2,'Aislantes','Térmicos','proveedores','quote',2),(v_m,v_s3,'Impermeabilización','Sistemas','proveedores','quote',3);
  INSERT INTO professional_portfolio (professional_id,title,description,category,project_date) VALUES (v_m,'Reforma hotel','Suministro 48 habitaciones','proveedores','2024-03-15');
  INSERT INTO professional_stats (professional_id,completed_bookings,total_reviews,average_rating) VALUES (v_m,156,89,4.8) ON CONFLICT (professional_id) DO NOTHING;
  IF NOT EXISTS (SELECT 1 FROM professional_verifications WHERE professional_id=v_m AND verification_method='id_document') THEN INSERT INTO professional_verifications (professional_id,verification_method,status,reviewed_at) VALUES (v_m,'id_document','approved',now()); END IF;
  IF NOT EXISTS (SELECT 1 FROM professional_verifications WHERE professional_id=v_m AND verification_method='business_license') THEN INSERT INTO professional_verifications (professional_id,verification_method,status,reviewed_at) VALUES (v_m,'business_license','approved',now()); END IF;
  SELECT id INTO v_b FROM auth.users WHERE email = 'demo+balear@ibizafair.com';
  IF v_b IS NULL THEN INSERT INTO auth.users (id,instance_id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change) VALUES (gen_random_uuid(),'00000000-0000-0000-0000-000000000000','demo+balear@ibizafair.com',crypt('Demo123!',gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{}',now(),now(),'','','','') RETURNING id INTO v_b; END IF;
  INSERT INTO profiles (id,full_name,phone) VALUES (v_b,'Suministros Balear','+34 600 589 204') ON CONFLICT (id) DO NOTHING;
  INSERT INTO user_roles (user_id,role) VALUES (v_b,'professional') ON CONFLICT DO NOTHING;
  INSERT INTO professional_profiles (user_id,business_name,primary_trade,bio,contact_phone,whatsapp,contact_email,social_links,experience_years,team_size,languages,emergency_service,max_projects_in_parallel,min_project_value,max_project_value,subsector_tags,unique_selling_points,ideal_clients,is_demo_profile,featured_at_events) VALUES (v_b,'Suministros Técnicos Balear','proveedores','Maquinaria, EPIs.','+34 600 589 204','+34 600 589 204','demo+balear@ibizafair.com','{"instagram":"https://instagram.com/balear"}'::jsonb,'10',9,'["ES","EN"]'::jsonb,true,10,50,15000,'["Maquinaria","EPIs"]'::jsonb,'["EPIs homologados"]'::jsonb,'Empresas',true,'["ibiza-fair-2025"]'::jsonb) ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO professional_service_items (professional_id,service_id,name,description,category,pricing_type,display_order) VALUES (v_b,v_s4,'Maquinaria ligera','Profesional','proveedores','quote',1),(v_b,v_s5,'EPIs','Homologados','proveedores','quote',2);
  INSERT INTO professional_portfolio (professional_id,title,description,category,project_date) VALUES (v_b,'Suministro resort','Equipamiento','proveedores','2024-05-10');
  INSERT INTO professional_stats (professional_id,completed_bookings,total_reviews,average_rating) VALUES (v_b,98,67,4.7) ON CONFLICT (professional_id) DO NOTHING;
  IF NOT EXISTS (SELECT 1 FROM professional_verifications WHERE professional_id=v_b AND verification_method='id_document') THEN INSERT INTO professional_verifications (professional_id,verification_method,status,reviewed_at) VALUES (v_b,'id_document','approved',now()); END IF;
  IF NOT EXISTS (SELECT 1 FROM professional_verifications WHERE professional_id=v_b AND verification_method='business_license') THEN INSERT INTO professional_verifications (professional_id,verification_method,status,reviewed_at) VALUES (v_b,'business_license','approved',now()); END IF;
END $$;