-- Insert Planning Drawings question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'planning-drawings', 1, 'approved', 'manual',
  $json${
    "id": "a5a25a9e-4a62-4f23-9478-6a4f15984c32",
    "category": "residential-architects",
    "name": "Planning Drawings",
    "slug": "planning-drawings",
    "i18nPrefix": "residentialArchitects.planningDrawings",
    "questions": [
      {"key": "submission_type", "type": "single", "i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.title", "required": true, "aiHint": "Type of planning submission the drawings are for.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.house_extension", "value": "house_extension", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.new_build", "value": "new_build", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.renovation", "value": "renovation", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.change_of_use", "value": "change_of_use", "order": 3}, {"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.outbuilding", "value": "outbuilding", "order": 4}, {"i18nKey": "residentialArchitects.planningDrawings.questions.submission_type.options.boundary_changes", "value": "boundary_changes", "order": 5}]},
      {"key": "required_drawings", "type": "multi", "i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.title", "required": true, "aiHint": "Which specific drawing types are needed for the planning submission.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.existing_plans", "value": "existing_plans", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.proposed_plans", "value": "proposed_plans", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.elevations", "value": "elevations", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.roof_plan", "value": "roof_plan", "order": 3}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.site_plan", "value": "site_plan", "order": 4}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.location_plan", "value": "location_plan", "order": 5}, {"i18nKey": "residentialArchitects.planningDrawings.questions.required_drawings.options.all", "value": "all", "order": 6}]},
      {"key": "detail_level", "type": "single", "i18nKey": "residentialArchitects.planningDrawings.questions.detail_level.title", "required": true, "aiHint": "Depth of architectural detail required for planning purposes.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.detail_level.options.basic_layouts", "value": "basic_layouts", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.detail_level.options.detailed_plans_elevations", "value": "detailed_plans_elevations", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.detail_level.options.full_planning_package", "value": "full_planning_package", "order": 2}]},
      {"key": "existing_drawings", "type": "single", "i18nKey": "residentialArchitects.planningDrawings.questions.existing_drawings.title", "required": true, "aiHint": "Whether the client already has existing drawings or surveys.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.existing_drawings.options.full_set_available", "value": "full_set_available", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.existing_drawings.options.partial_set_available", "value": "partial_set_available", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.existing_drawings.options.no_drawings", "value": "no_drawings", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.existing_drawings.options.rough_sketches_only", "value": "rough_sketches_only", "order": 3}]},
      {"key": "follow_guidelines", "type": "single", "i18nKey": "residentialArchitects.planningDrawings.questions.follow_guidelines.title", "required": true, "aiHint": "How strictly the design should follow local planning guidelines.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.follow_guidelines.options.strict_compliance", "value": "strict_compliance", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.follow_guidelines.options.flexible_compliance", "value": "flexible_compliance", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.follow_guidelines.options.creative_design", "value": "creative_design", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.follow_guidelines.options.not_sure", "value": "not_sure", "order": 3}]},
      {"key": "constraints", "type": "multi", "i18nKey": "residentialArchitects.planningDrawings.questions.constraints.title", "required": true, "aiHint": "Site or legal constraints that must be considered and shown on drawings.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.party_walls", "value": "party_walls", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.protected_areas", "value": "protected_areas", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.height_limits", "value": "height_limits", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.neighbouring_windows", "value": "neighbouring_windows", "order": 3}, {"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.none", "value": "none", "order": 4}, {"i18nKey": "residentialArchitects.planningDrawings.questions.constraints.options.unsure", "value": "unsure", "order": 5}]},
      {"key": "primary_goal", "type": "single", "i18nKey": "residentialArchitects.planningDrawings.questions.primary_goal.title", "required": true, "aiHint": "Main priority for the planning drawings from the client perspective.", "options": [{"i18nKey": "residentialArchitects.planningDrawings.questions.primary_goal.options.approval_certainty", "value": "approval_certainty", "order": 0}, {"i18nKey": "residentialArchitects.planningDrawings.questions.primary_goal.options.fast_submission", "value": "fast_submission", "order": 1}, {"i18nKey": "residentialArchitects.planningDrawings.questions.primary_goal.options.exploring_design_options", "value": "exploring_design_options", "order": 2}, {"i18nKey": "residentialArchitects.planningDrawings.questions.primary_goal.options.visual_clarity_for_discussions", "value": "visual_clarity_for_discussions", "order": 3}]}
    ]
  }$json$::jsonb, true, now()
);

-- Insert Load Assessment question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'load-assessment', 1, 'approved', 'manual',
  $json${
    "id": "5d3e5f12-1f9a-4ba5-9aa7-9c9a35841ad1",
    "category": "structural-engineers",
    "name": "Load Assessment",
    "slug": "load-assessment",
    "i18nPrefix": "structuralEngineers.loadAssessment",
    "questions": [
      {"key": "load_type", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.load_type.title", "required": true, "aiHint": "Type of load or structural concern being assessed.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.floor_load", "value": "floor_load", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.beam_load", "value": "beam_load", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.roof_load", "value": "roof_load", "order": 2}, {"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.wall_support", "value": "wall_support", "order": 3}, {"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.opening_removal", "value": "opening_removal", "order": 4}, {"i18nKey": "structuralEngineers.loadAssessment.questions.load_type.options.unsure", "value": "unsure", "order": 5}]},
      {"key": "reason_for_assessment", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.title", "required": true, "aiHint": "Why the client needs a load assessment.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.options.renovation", "value": "renovation", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.options.extension", "value": "extension", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.options.structural_concern", "value": "structural_concern", "order": 2}, {"i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.options.new_opening", "value": "new_opening", "order": 3}, {"i18nKey": "structuralEngineers.loadAssessment.questions.reason_for_assessment.options.change_of_use", "value": "change_of_use", "order": 4}]},
      {"key": "structural_element", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.title", "required": true, "aiHint": "Which structural element needs load evaluation.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.options.floor_joists", "value": "floor_joists", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.options.beams_rsjs", "value": "beams_rsjs", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.options.roof_trusses", "value": "roof_trusses", "order": 2}, {"i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.options.load_bearing_wall", "value": "load_bearing_wall", "order": 3}, {"i18nKey": "structuralEngineers.loadAssessment.questions.structural_element.options.foundation_zone", "value": "foundation_zone", "order": 4}]},
      {"key": "known_dimensions", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.known_dimensions.title", "required": true, "aiHint": "Whether the client knows the basic dimensions of the structural element.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.known_dimensions.options.full_dimensions", "value": "full_dimensions", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.known_dimensions.options.partial_dimensions", "value": "partial_dimensions", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.known_dimensions.options.no_dimensions", "value": "no_dimensions", "order": 2}]},
      {"key": "construction_material", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.title", "required": true, "aiHint": "Primary material involved in the structural element being assessed.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.options.timber", "value": "timber", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.options.steel", "value": "steel", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.options.concrete", "value": "concrete", "order": 2}, {"i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.options.masonry", "value": "masonry", "order": 3}, {"i18nKey": "structuralEngineers.loadAssessment.questions.construction_material.options.unknown", "value": "unknown", "order": 4}]},
      {"key": "additional_loads", "type": "multi", "i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.title", "required": true, "aiHint": "Any special loads that need to be considered in the assessment.", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.options.heavy_equipment", "value": "heavy_equipment", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.options.storage_loads", "value": "storage_loads", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.options.hvac_units", "value": "hvac_units", "order": 2}, {"i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.options.water_tanks", "value": "water_tanks", "order": 3}, {"i18nKey": "structuralEngineers.loadAssessment.questions.additional_loads.options.none", "value": "none", "order": 4}]},
      {"key": "urgency_level", "type": "single", "i18nKey": "structuralEngineers.loadAssessment.questions.urgency_level.title", "required": true, "aiHint": "How urgent the structural load assessment is (not time-specific).", "options": [{"i18nKey": "structuralEngineers.loadAssessment.questions.urgency_level.options.immediate_concern", "value": "immediate_concern", "order": 0}, {"i18nKey": "structuralEngineers.loadAssessment.questions.urgency_level.options.planned_project", "value": "planned_project", "order": 1}, {"i18nKey": "structuralEngineers.loadAssessment.questions.urgency_level.options.early_stage_enquiry", "value": "early_stage_enquiry", "order": 2}]}
    ]
  }$json$::jsonb, true, now()
);

-- Insert Structural Calculations question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'structural-calculations', 1, 'approved', 'manual',
  $json${
    "id": "b4e57c98-ae4d-4f89-9e36-ef32d580a4b1",
    "category": "structural-engineers",
    "name": "Structural Calculations",
    "slug": "structural-calculations",
    "i18nPrefix": "structuralEngineers.structuralCalculations",
    "questions": [
      {"key": "calculation_type", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.title", "required": true, "aiHint": "Type of structural calculations required for the project.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.beam_sizing", "value": "beam_sizing", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.load_bearing_wall_removal", "value": "load_bearing_wall_removal", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.floor_load_analysis", "value": "floor_load_analysis", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.roof_load_analysis", "value": "roof_load_analysis", "order": 3}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.foundation_design", "value": "foundation_design", "order": 4}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_type.options.full_structural_package", "value": "full_structural_package", "order": 5}]},
      {"key": "project_stage", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.project_stage.title", "required": true, "aiHint": "How far the project is developed before calculations.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.project_stage.options.sketch_stage", "value": "sketch_stage", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.project_stage.options.plans_ready", "value": "plans_ready", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.project_stage.options.design_finalised", "value": "design_finalised", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.project_stage.options.structural_changes_only", "value": "structural_changes_only", "order": 3}]},
      {"key": "structural_elements_involved", "type": "multi", "i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.title", "required": true, "aiHint": "Structural elements that calculations must cover.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.beams", "value": "beams", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.columns", "value": "columns", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.joists", "value": "joists", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.load_bearing_walls", "value": "load_bearing_walls", "order": 3}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.roof_trusses", "value": "roof_trusses", "order": 4}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.structural_elements_involved.options.foundation_zones", "value": "foundation_zones", "order": 5}]},
      {"key": "material_type", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.title", "required": true, "aiHint": "Main construction material(s) the calculations must apply to.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.options.timber", "value": "timber", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.options.steel", "value": "steel", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.options.concrete", "value": "concrete", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.options.masonry", "value": "masonry", "order": 3}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.material_type.options.mixed_materials", "value": "mixed_materials", "order": 4}]},
      {"key": "existing_info_available", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.existing_info_available.title", "required": true, "aiHint": "What structural information or drawings the client already has.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.existing_info_available.options.full_structural_drawings", "value": "full_structural_drawings", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.existing_info_available.options.partial_drawings", "value": "partial_drawings", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.existing_info_available.options.no_drawings", "value": "no_drawings", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.existing_info_available.options.basic_sketches", "value": "basic_sketches", "order": 3}]},
      {"key": "complexity_level", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.complexity_level.title", "required": true, "aiHint": "How complex the structural calculation requirements are expected to be.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.complexity_level.options.standard", "value": "standard", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.complexity_level.options.intermediate", "value": "intermediate", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.complexity_level.options.high_complexity", "value": "high_complexity", "order": 2}]},
      {"key": "calculation_goal", "type": "single", "i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.title", "required": true, "aiHint": "Primary purpose for requiring the structural calculations.", "options": [{"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.options.building_safety", "value": "building_safety", "order": 0}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.options.regulation_compliance", "value": "regulation_compliance", "order": 1}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.options.renovation_support", "value": "renovation_support", "order": 2}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.options.extension_support", "value": "extension_support", "order": 3}, {"i18nKey": "structuralEngineers.structuralCalculations.questions.calculation_goal.options.full_design_package", "value": "full_design_package", "order": 4}]}
    ]
  }$json$::jsonb, true, now()
);

-- Insert AC Emergency Repair question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'ac-emergency-repair', 1, 'approved', 'manual',
  $json${
    "id": "d2f1bb35-0c7d-4a16-9c33-5c9f1c6fe001",
    "category": "hvac",
    "name": "AC Emergency Repair",
    "slug": "ac-emergency-repair",
    "i18nPrefix": "hvac.acEmergencyRepair",
    "questions": [
      {"key": "system_type", "type": "single", "i18nKey": "hvac.acEmergencyRepair.questions.system_type.title", "required": true, "aiHint": "Type of AC system that needs emergency repair.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.split_wall_unit", "value": "split_wall_unit", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.multi_split", "value": "multi_split", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.ducted_system", "value": "ducted_system", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.cassette_ceiling_unit", "value": "cassette_ceiling_unit", "order": 3}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.window_unit", "value": "window_unit", "order": 4}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.portable_unit", "value": "portable_unit", "order": 5}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_type.options.unsure", "value": "unsure", "order": 6}]},
      {"key": "main_issue", "type": "single", "i18nKey": "hvac.acEmergencyRepair.questions.main_issue.title", "required": true, "aiHint": "Primary symptom or emergency issue with the AC.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.no_power", "value": "no_power", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.no_cooling", "value": "no_cooling", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.only_warm_air", "value": "only_warm_air", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.water_leak", "value": "water_leak", "order": 3}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.burning_smell_or_smoke", "value": "burning_smell_or_smoke", "order": 4}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.unusual_noise", "value": "unusual_noise", "order": 5}, {"i18nKey": "hvac.acEmergencyRepair.questions.main_issue.options.electric_trip", "value": "electric_trip", "order": 6}]},
      {"key": "system_status", "type": "single", "i18nKey": "hvac.acEmergencyRepair.questions.system_status.title", "required": true, "aiHint": "Current operating status of the AC system.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.system_status.options.completely_off", "value": "completely_off", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_status.options.turns_on_then_cuts_out", "value": "turns_on_then_cuts_out", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_status.options.running_but_not_cooling", "value": "running_but_not_cooling", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.system_status.options.running_with_leaks_or_smells", "value": "running_with_leaks_or_smells", "order": 3}]},
      {"key": "units_affected", "type": "single", "i18nKey": "hvac.acEmergencyRepair.questions.units_affected.title", "required": true, "aiHint": "How many indoor units are affected by the emergency issue.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.units_affected.options.single_indoor_unit", "value": "single_indoor_unit", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.units_affected.options.several_indoor_units", "value": "several_indoor_units", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.units_affected.options.all_units_on_system", "value": "all_units_on_system", "order": 2}]},
      {"key": "error_indicators", "type": "multi", "i18nKey": "hvac.acEmergencyRepair.questions.error_indicators.title", "required": true, "aiHint": "Any error lights, codes or electrical issues noticed.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.error_indicators.options.flashing_lights", "value": "flashing_lights", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.error_indicators.options.error_code_displayed", "value": "error_code_displayed", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.error_indicators.options.breaker_trips", "value": "breaker_trips", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.error_indicators.options.no_error_indicators", "value": "no_error_indicators", "order": 3}]},
      {"key": "recent_changes", "type": "multi", "i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.title", "required": true, "aiHint": "Recent events that could be linked to the sudden failure.", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.options.recent_installation", "value": "recent_installation", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.options.recent_service", "value": "recent_service", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.options.recent_renovation_nearby", "value": "recent_renovation_nearby", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.options.power_outage_or_surge", "value": "power_outage_or_surge", "order": 3}, {"i18nKey": "hvac.acEmergencyRepair.questions.recent_changes.options.no_recent_changes", "value": "no_recent_changes", "order": 4}]},
      {"key": "impact_severity", "type": "single", "i18nKey": "hvac.acEmergencyRepair.questions.impact_severity.title", "required": true, "aiHint": "How seriously the issue is affecting the space (comfort or safety).", "options": [{"i18nKey": "hvac.acEmergencyRepair.questions.impact_severity.options.safety_concern", "value": "safety_concern", "order": 0}, {"i18nKey": "hvac.acEmergencyRepair.questions.impact_severity.options.space_unusable", "value": "space_unusable", "order": 1}, {"i18nKey": "hvac.acEmergencyRepair.questions.impact_severity.options.major_comfort_issue", "value": "major_comfort_issue", "order": 2}, {"i18nKey": "hvac.acEmergencyRepair.questions.impact_severity.options.inconvenient_but_usable", "value": "inconvenient_but_usable", "order": 3}]}
    ]
  }$json$::jsonb, true, now()
);

-- Insert AC Gas Recharge question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'ac-gas-recharge', 1, 'approved', 'manual',
  $json${
    "id": "7b3c0d96-62f0-4f9f-bf46-2fa66a0a9b02",
    "category": "hvac",
    "name": "AC Gas Recharge",
    "slug": "ac-gas-recharge",
    "i18nPrefix": "hvac.acGasRecharge",
    "questions": [
      {"key": "system_type", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.system_type.title", "required": true, "aiHint": "Type of AC system needing a refrigerant recharge.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.system_type.options.split_wall_unit", "value": "split_wall_unit", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.system_type.options.multi_split", "value": "multi_split", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.system_type.options.ducted_system", "value": "ducted_system", "order": 2}, {"i18nKey": "hvac.acGasRecharge.questions.system_type.options.cassette_ceiling_unit", "value": "cassette_ceiling_unit", "order": 3}, {"i18nKey": "hvac.acGasRecharge.questions.system_type.options.window_unit", "value": "window_unit", "order": 4}]},
      {"key": "cooling_issue", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.cooling_issue.title", "required": true, "aiHint": "Cooling performance issue that suggests low refrigerant.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.cooling_issue.options.not_cold_enough", "value": "not_cold_enough", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.cooling_issue.options.takes_too_long_to_cool", "value": "takes_too_long_to_cool", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.cooling_issue.options.only_cool_in_certain_areas", "value": "only_cool_in_certain_areas", "order": 2}, {"i18nKey": "hvac.acGasRecharge.questions.cooling_issue.options.unit_keeps_running_nonstop", "value": "unit_keeps_running_nonstop", "order": 3}]},
      {"key": "visible_symptoms", "type": "multi", "i18nKey": "hvac.acGasRecharge.questions.visible_symptoms.title", "required": true, "aiHint": "Visible signs related to potential low gas or refrigeration issues.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.visible_symptoms.options.ice_on_pipes_or_coils", "value": "ice_on_pipes_or_coils", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.visible_symptoms.options.water_dripping_from_indoor_unit", "value": "water_dripping_from_indoor_unit", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.visible_symptoms.options.oil_stains_near_connections", "value": "oil_stains_near_connections", "order": 2}, {"i18nKey": "hvac.acGasRecharge.questions.visible_symptoms.options.no_special_signs", "value": "no_special_signs", "order": 3}]},
      {"key": "refrigerant_known", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.refrigerant_known.title", "required": true, "aiHint": "Whether the client knows the refrigerant type used in the system.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.refrigerant_known.options.r410a", "value": "r410a", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.refrigerant_known.options.r32", "value": "r32", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.refrigerant_known.options.other_marked_on_label", "value": "other_marked_on_label", "order": 2}, {"i18nKey": "hvac.acGasRecharge.questions.refrigerant_known.options.not_known", "value": "not_known", "order": 3}]},
      {"key": "previous_gas_issues", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.previous_gas_issues.title", "required": true, "aiHint": "History of gas or refrigerant-related issues.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.previous_gas_issues.options.never_had_gas_issue", "value": "never_had_gas_issue", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.previous_gas_issues.options.had_recharge_once", "value": "had_recharge_once", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.previous_gas_issues.options.repeated_gas_topups", "value": "repeated_gas_topups", "order": 2}]},
      {"key": "units_needing_recharge", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.units_needing_recharge.title", "required": true, "aiHint": "Scope of work in terms of number of units to recharge.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.units_needing_recharge.options.single_indoor_unit", "value": "single_indoor_unit", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.units_needing_recharge.options.several_indoor_units", "value": "several_indoor_units", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.units_needing_recharge.options.full_system_all_units", "value": "full_system_all_units", "order": 2}]},
      {"key": "time_since_last_service", "type": "single", "i18nKey": "hvac.acGasRecharge.questions.time_since_last_service.title", "required": true, "aiHint": "How long it has roughly been since any AC service was done.", "options": [{"i18nKey": "hvac.acGasRecharge.questions.time_since_last_service.options.within_last_year", "value": "within_last_year", "order": 0}, {"i18nKey": "hvac.acGasRecharge.questions.time_since_last_service.options.one_to_three_years", "value": "one_to_three_years", "order": 1}, {"i18nKey": "hvac.acGasRecharge.questions.time_since_last_service.options.more_than_three_years", "value": "more_than_three_years", "order": 2}, {"i18nKey": "hvac.acGasRecharge.questions.time_since_last_service.options.never_serviced", "value": "never_serviced", "order": 3}]}
    ]
  }$json$::jsonb, true, now()
);

-- Insert AC Leak Detection & Repair question pack
INSERT INTO question_packs (pack_id, micro_slug, version, status, source, content, is_active, created_at)
VALUES (
  gen_random_uuid(), 'ac-leak-detection-repair', 1, 'approved', 'manual',
  $json${
    "id": "3c7af7f4-9c9e-4e26-8ef9-29b8f0c0b803",
    "category": "hvac",
    "name": "AC Leak Detection & Repair",
    "slug": "ac-leak-detection-repair",
    "i18nPrefix": "hvac.acLeakDetectionRepair",
    "questions": [
      {"key": "suspected_leak_type", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.suspected_leak_type.title", "required": true, "aiHint": "Whether the concern is refrigerant leak, water leak or both.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.suspected_leak_type.options.refrigerant_gas_leak", "value": "refrigerant_gas_leak", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.suspected_leak_type.options.water_leak_from_indoor_unit", "value": "water_leak_from_indoor_unit", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.suspected_leak_type.options.water_leak_from_pipes_or_drain", "value": "water_leak_from_pipes_or_drain", "order": 2}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.suspected_leak_type.options.not_sure", "value": "not_sure", "order": 3}]},
      {"key": "leak_location", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.title", "required": true, "aiHint": "Where the leak appears to be coming from.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.options.indoor_unit_front_or_bottom", "value": "indoor_unit_front_or_bottom", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.options.near_outdoor_unit", "value": "near_outdoor_unit", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.options.along_pipes_or_trunking", "value": "along_pipes_or_trunking", "order": 2}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.options.from_ceiling_or_wall_area", "value": "from_ceiling_or_wall_area", "order": 3}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_location.options.unclear", "value": "unclear", "order": 4}]},
      {"key": "visible_signs", "type": "multi", "i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.title", "required": true, "aiHint": "Visible signs that help identify the nature of the leak.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.dripping_water", "value": "dripping_water", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.water_stains_or_damage", "value": "water_stains_or_damage", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.ice_on_pipes_or_indoor_unit", "value": "ice_on_pipes_or_indoor_unit", "order": 2}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.oil_traces_near_connections", "value": "oil_traces_near_connections", "order": 3}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.damp_smell_or_mildew", "value": "damp_smell_or_mildew", "order": 4}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.visible_signs.options.no_visible_signs", "value": "no_visible_signs", "order": 5}]},
      {"key": "system_performance_effect", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.system_performance_effect.title", "required": true, "aiHint": "How the leak is affecting AC cooling performance.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.system_performance_effect.options.cooling_normal", "value": "cooling_normal", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.system_performance_effect.options.slightly_reduced_cooling", "value": "slightly_reduced_cooling", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.system_performance_effect.options.significantly_reduced_cooling", "value": "significantly_reduced_cooling", "order": 2}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.system_performance_effect.options.no_cooling", "value": "no_cooling", "order": 3}]},
      {"key": "units_affected", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.units_affected.title", "required": true, "aiHint": "How many units are showing leak-related symptoms.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.units_affected.options.single_indoor_unit", "value": "single_indoor_unit", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.units_affected.options.multiple_indoor_units", "value": "multiple_indoor_units", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.units_affected.options.all_units", "value": "all_units", "order": 2}]},
      {"key": "previous_repairs", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.previous_repairs.title", "required": true, "aiHint": "History of any previous leak-related repairs on the system.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.previous_repairs.options.no_previous_leak_repairs", "value": "no_previous_leak_repairs", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.previous_repairs.options.one_prior_leak_repair", "value": "one_prior_leak_repair", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.previous_repairs.options.repeated_leak_repairs", "value": "repeated_leak_repairs", "order": 2}]},
      {"key": "leak_impact_severity", "type": "single", "i18nKey": "hvac.acLeakDetectionRepair.questions.leak_impact_severity.title", "required": true, "aiHint": "How serious the leak is in terms of damage risk and disruption.", "options": [{"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_impact_severity.options.risk_of_property_damage", "value": "risk_of_property_damage", "order": 0}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_impact_severity.options.constant_dripping_but_managed", "value": "constant_dripping_but_managed", "order": 1}, {"i18nKey": "hvac.acLeakDetectionRepair.questions.leak_impact_severity.options.annoying_but_minor", "value": "annoying_but_minor", "order": 2}]}
    ]
  }$json$::jsonb, true, now()
);